# Adjust these settings if you like:
title: >-
  Diasporas on Stolen Land
description: >-
  A decolonial zine written by BIMPOC for BIMPOC
color: "#CEB193"

# Change this to whatever your real URL is, if you get one
url: "http://diasporasonstolenland.github.io"

# Probably don't touch these ones
markdown: kramdown
baseurl: ""
