# Adjust these settings if you like:
title: >-
  Diasporas on Stolen Land
description: >-
  Welcome! Thank you for coming to check out our website and share in building community through solidarity. We invite you to explore this website and check out what this project is all about, the zine we created, and to explore some additional resources. 
color: "#CEB193"

# Change this to whatever your real URL is, if you get one
url: "http://diasporasonstolenland.github.io"

# Probably don't touch these ones
markdown: kramdown
baseurl: ""
